# -*- coding: utf-8 -*-
"""eqity info.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aMJMLfGCRER6pfyC_dLmqnEjQFjTpeph
"""

!pip install requests
!pip install beautifulsoup4
!pip install langchain
!pip install chromadb
!pip install sentence-transformers
!pip install groq
!pip install sentence-transformers
!pip install groq
!pip install langchain-text-splitters
!pip install streamlit



!pip install newspaper3k
!pip install lxml_html_clean

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embeddings model loaded successfully")



from newspaper import Article

url = input("Enter article URL: ")

article = Article(url)

article.download()
article.parse()

print("TITLE:")
print(article.title)

print("\nARTICLE:\n")
print(article.text[:70000])

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=3000,
    chunk_overlap=200
)

chunks = splitter.split_text(article.text)

print("Number of chunks:", len(chunks))

print("\nFirst Chunk:\n")
print(chunks[0])

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = model.encode(chunks)

print("Number of embeddings:", len(embeddings))
print("Embedding dimension:", len(embeddings[0]))

import chromadb

client = chromadb.Client()

collection = client.create_collection(
    name="article_chunkSSS"
)

for i, chunk in enumerate(chunks):
    collection.add(
        ids=[str(i)],
        embeddings=[embeddings[i].tolist()],
        documents=[chunk]
    )

print("Stored", len(chunks), "chunks in ChromaDB")

question = "STOCKS TO BUY TODAY?"

query_embedding = model.encode(question)

results = collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=2
)

print(results["documents"][0])

from groq import Groq

client = Groq(
    api_key= ""
)

question = "STOCKS TO BUY TODAY?"

query_embedding = model.encode(question)

results = collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=2
)

context = "\n".join(results["documents"][0])

prompt = f"""
Answer the question ONLY using the context below.

Context:
{context}

Question:
{question}
"""

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "user",
            "content": prompt
        }
    ]
)

print(response.choices[0].message.content)

print("\nRetrieved Context:\n")
print(context)

print("\nAnswer:\n")
print(response.choices[0].message.content)

while True:
    question = input("\nAsk a question: ")

    if question.lower() == "exit":
        print("Goodbye!")
        break

    query_embedding = model.encode(question)

    results = collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=3
    )

    context = "\n".join(results["documents"][0])

    prompt = f"""
    Answer ONLY from the provided context.

    Context:
    {context}

    Question:
    {question}
    """

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    print("\nAnswer:")
    print(response.choices[0].message.content)

